### ISSUE TITLE
Unable to import even on Python 2.7.5

### ISSUE THREAD

**Issue by janit92** [bguillouet/traj-dist#3]
>>> import traj_dist.distance as tdist
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "traj_dist/distance.py", line 3, in <module>
    from cydist.sspd import c_e_sspd, c_g_sspd
ImportError: No module named sspd

From earlier issues - it seems Python 3 is not supported. But I am installing it in an environment with Python 2.7.5 still gives the above error. Please help to resolve the same.

**Comment by janit92** [comment]
Looks like I resolved the issue.

**Comment by jdzejdzej** [comment]
> Looks like I resolved the issue.

What did you do to resolve this issue on python 2.7 ?
